name: スポーツくじ繰越金チェック

on:
  schedule:
    - cron: '0 2 * * *'  # 매일 오전 11시 (한국시간)
  workflow_dispatch:

jobs:
  check-carryover:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 의존성 설치
        run: pip install beautifulsoup4 requests

      - name: 최신 HTML 저장 (셀레니움 대신 wget 사용 가능 시 대체)
        run: curl -o toto_debug.html "http://www.toto-dream.com/dci/I/IPB/IPB02.do?op=initLotResultDetBIG&popupDispDiv=disp"

      - name: 이월금 스크립트 실행
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python extract_carryovers.py
