name: Check Carryovers

on:
  schedule:
    - cron: '37 5 * * *'  # JST 14:37
    - cron: '57 13 * * *'  # JST 22:57
  workflow_dispatch:

permissions:
  issues: write

jobs:
  carryover-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 selenium requests

      - name: Run carryover extractor
        run: python extract_carryovers.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
